### ISSUE TITLE
Layout: update main content width

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/platypus#1249]
### Feature description

Currently, for screens at the max breakpoint and above, the textbook content has a maximum width of 42rem.

This issue is to increase the width.

```scss
.c-textbook__content {
    max-width: 46rem; // 👈 this
    padding: 0 1.5rem 1rem 1rem;
}
```

Tasks:
- [ ] increase content panel width
- [ ] ensure all widgets are still rendering as expected

**Note:**
The scratchpad feature is not dependent on this issue.
